// Package store persists users, conversations and messages.
//
// The Store interface is the seam for swapping SQLite for Postgres later: the
// hub and HTTP handlers only ever see this interface, so a production
// migration touches one package.
package store

import (
	"context"
	"errors"
	"time"
)

var (
	ErrNotFound = errors.New("store: not found")
	// ErrClientMsgIDReused means the sender reused a clientMsgId for a
	// different conversation than the one it was first used in.
	ErrClientMsgIDReused = errors.New("store: clientMsgId already used in another conversation")
)

type User struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"createdAt"`
}

type Message struct {
	// ID is assigned by the database and is monotonic per table. It is the
	// only ordering the system trusts — client clocks are not comparable.
	ID             int64  `json:"id"`
	ConversationID int64  `json:"conversationId"`
	SenderID       int64  `json:"senderId"`
	RecipientID    int64  `json:"recipientId"`
	Body           string `json:"body"`
	// ClientMsgID is generated by the sender; resending with the same value
	// is a no-op so retries after a dropped ack cannot duplicate a message.
	ClientMsgID string    `json:"clientMsgId"`
	CreatedAt   time.Time `json:"createdAt"`
}

type Store interface {
	// UpsertUser returns the existing user with that name or creates one.
	UpsertUser(ctx context.Context, username string) (User, error)
	GetUser(ctx context.Context, id int64) (User, error)
	// ListUsers returns everyone ordered by username.
	ListUsers(ctx context.Context) ([]User, error)

	// AppendMessage stores a message between two users, creating their
	// conversation on first contact. If (sender, clientMsgID) was already
	// stored the existing message is returned and duplicate is true.
	AppendMessage(ctx context.Context, senderID, recipientID int64, body, clientMsgID string) (msg Message, duplicate bool, err error)
	// ListMessages returns up to limit messages between the two users with
	// ID greater than afterID, oldest first. Cursor pagination on the ID
	// (rather than OFFSET) stays correct while new rows are being inserted.
	ListMessages(ctx context.Context, userA, userB, afterID int64, limit int) ([]Message, error)

	Close() error
}
